### ISSUE TITLE
Vulkaninfo doesn't detect VK_KHR_present_id and VK_KHR_present_wait extensions

### ISSUE THREAD

**Issue by arunsivaramanneo** [KhronosGroup/Vulkan-Tools#757] opened 2023-03-14 20:50 UTC
Not sure if this an issue with vulkaninfo as i don't see VK_KHR_present_id and VK_KHR_present_wait extensions  supported whereas VulkanCapsViewer Shows its supported. please see screenshot below and attached Vulkaninfo extract. 

![Screenshot from 2023-03-14 20-47-31](https://user-images.githubusercontent.com/30646692/225132645-7254959b-b03c-4895-98ff-a4acb91e2fee.png)

[vulkanino.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/10973592/vulkanino.txt)

**Comment by charles-lunarg** [comment] 2023-03-14 20:56
Vulkaninfo doesn't do any sort of processing of the extension list. 

Looking at the source code of mesa, I would reckon that the issue is that mesa isn't exposing the extension unless all enabled surface extensions support it.
> If the instance only enables surface extensions that unconditionally support present wait,
       * we can also expose the extension that way.
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/amd/vulkan/radv_physical_device.c#L457

I know this to be a possibility because vulkaninfo enables *all* instance extensions it finds.

**Comment by charles-lunarg** [comment] 2023-03-14 21:00
Digging further, if wayland is enabled, then the present wait feature is not.
https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common.c#L1466

**Comment by arunsivaramanneo** [comment] 2023-03-14 21:11
I did check  in X11 the extensions are not listed.So until Mesa expose it this will not be shown in the vulkaninfo extensions. thanks for looking into it

**Comment by charles-lunarg** [comment] 2023-03-14 21:11
I just had a peak at the VulkanCapsViewer source. It appears that it also enables all instance extensions, which is a real :wat: moment.

Is KHR_wayland_surface in your VulkanCapsViewer list of instance extensions?

**Comment by charles-lunarg** [comment] 2023-03-14 21:12
The mesa code makes it seem like wayland is the reason they can't support it, not X11.

**Comment by arunsivaramanneo** [comment] 2023-03-14 21:15
> I just had a peak at the VulkanCapsViewer source. It appears that it also enables all instance extensions, which is a real :wat: moment.
> 
> Is KHR_wayland_surface in your VulkanCapsViewer list of instance extensions?

Yes i can see the KHR_Wayland_surface in instances

![Screenshot from 2023-03-14 21-14-08](https://user-images.githubusercontent.com/30646692/225137882-9db355f9-6005-4f12-8303-a6aaacf26c6c.png)

**Comment by arunsivaramanneo** [comment] 2023-03-15 04:13
So is this an issue or is it as expected ?

**Comment by versalinyaa** [comment] 2023-03-29 16:48
I will begin digging into Mesa's WSI code next week to try to understand what's happening and why.

**Comment by arunsivaramanneo** [comment] 2024-02-13 09:15
Looks like this is now fixed now ... I can see they have enabled for Wayland and i can confirm i can see these extensions in Vulkaninfo report

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27275

**Comment by charles-lunarg** [comment] 2024-02-13 13:54
I'm going to close the issue as it appears like it is resolved. Thank you for updating the issue!

**Closed by charles-lunarg** 2024-02-13 13:54 UTC
Labels: vulkaninfo
