### ISSUE TITLE
vulkaninfo fails while vkcube works

### ISSUE THREAD

**Issue by spundun** [KhronosGroup/Vulkan-Tools#659] opened 2022-06-12 01:29 UTC
`vulkaninfo` fails with the following error...

```
$ vulkaninfo 
ERROR at /home/spundun/svntogit-packages-mesa/trunk/src/Vulkan-Tools-1.3.216/vulkaninfo/vulkaninfo.h:231:vkGetPhysicalDeviceSurfaceFormats2KHR failed with ERROR_SURFACE_LOST_KHR
```

`vkcube` succeeds with the following output
```
$ vkcube
Selected GPU 0: Virtio-GPU Venus (Intel(R) HD Graphics 615 (KBL GT2)), type: IntegratedGpu
```

I've installed this package on arch-linux running in a virtual machine on a chrome-os laptop. Vulkan is supposed to work through Virtio vulkan driver.

I've installed latest upstream releases of mesa and vulkan-headers and vulkan info by patching the `PKGINFO` for all those packages locally
* You can find my patch to update those packages to the latest version(22.1.1 with virtio drivers for mesa, and 1.3.216 for vulkan-headers/tools) in my gist here: https://gist.github.com/spundun/0fefb599352ef0082883512ce9a4c5bd
* I mostly followed this guide to install Arch Linux and Vulkan on Crostini : https://github.com/judjdigj/Vulkan_in_Crostini
  * Notice that the author of this guide also faced the same exact problem with `vulkaninfo`: https://github.com/judjdigj/Vulkan_in_Crostini/blob/main/README.md?plain=1#L139-L147
  * That guide is nearly the same as https://wiki.archlinux.org/title/Chrome_OS_devices/Crostini
  * I first used mesa-git but then decided to patch the stable package instead to improve the packaging for everyone.

**Comment by charles-lunarg** [comment] 2022-06-20 14:49
Is there any additional information you can provide about the system it is running on? I see that its erroring on `vkGetPhysicalDeviceSurfaceFormats2KHR`, however because it is passing through the virtio driver theres plenty of other things that could be wrong. Since the error is `ERROR_SURFACE_LOST_KHR`, it originates from the driver. Whether vulkaninfo is correctly using the function is another matter, though so far I have no reason to believe vulkaninfo is incorrect here. Running vulkaninfo with validation layers (you can use vkconfig to enable them globally) would be a good thing to do

`vkGetPhysicalDeviceSurfaceFormats2KHR` requires that the `VK_KHR_get_surface_capabilities2` extension is supported. Since that is an instance extension, this issue could be caused by 1 driver supporting that extension, while the driver you are using does not. Thus, it errors when it is called. 

The vulkan-loader 'emulates' the call if the function isn't supported, source [here](https://github.com/KhronosGroup/Vulkan-Loader/blob/e26be655eb804381e6fe081f84a95681f4daeef4/loader/wsi.c#L2584). It is conceivable that the 'emulation' code is wrong, and causing the issue, if indeed emulation is happening.

Can you run vulkaninfo with the env-var `VK_LOADER_DEBUG=all` set? And attach the output here. That way the loader knows to report all messages.

**Comment by spundun** [comment] 2022-06-21 03:21
Thanks for the response! Ack, on there being other moving parts(I'm no expert but it seems things in the way could be virtio venus driver, sommelier wayland server, VirGL rendere, does vulkaninfo use X11? then also XWayland, I guess?).

Here's the output you requested.

https://gist.github.com/spundun/1010984b5e56100de9c4c19ea09e27a7

**Comment by spundun** [comment] 2022-06-22 05:28
After I patched `vulkaninfo` with #663, it only fails on one extension(`VK_KHR_wayland_surface`) and is able to output the rest of the information.

`ERROR while creating surface for extension VK_KHR_wayland_surface : /home/spundun/svntogit-packages/trunk/src/Vulkan-Tools-1.3.217/vulkaninfo/vulkaninfo.h:231:vkGetPhysicalDeviceSurfaceFormats2KHR failed with ERROR_SURFACE_LOST_KHR`

Any thoughts on the next steps here? Should I take this up with [mesa](https://github.com/mesa3d/mesa) ?

**Comment by charles-lunarg** [comment] 2022-06-22 16:17
I think there definitely is some driver issue at the heart of this, but making vulkaninfo not *die* is exactly the solution vulkaninfo should have to work around the issue, greatly appreciate you going ahead and making a PR.

Virtio is in active development, so I would think that make a mesa issue is a good next step. (and probably close this issue after wards because its very likely an issue on their end.)

**Comment by spundun** [comment] 2022-06-22 18:01
Oh, forgot to include the vulkaninfo output, https://gist.github.com/spundun/f2c5a57bb90acb3848d274357e5cc725 in case that has any more hints as to the underlying issue.

My best guess is that there's a gap in the negotiation between mesa-virtio(the vulkan driver)/sommelier(wayland server)/VirGL(the Venus renderer that mesa and sommelier should be talking to) I might be missing a component here, I'm not sure what handles compositing on the host side, I'm assuming it's VirGL but it could be yet another component.

**Closed** 2022-06-24 19:15 UTC

**Comment by charles-lunarg** [comment] 2022-06-27 17:11
Thanks for making the issue there and creating a reproducible! That will definitely help the Mesa devs figure out what’s going on.
