### ISSUE TITLE
vkcube always uses the X11 WSI.

### ISSUE THREAD

**Issue by kkartaltepe** [KhronosGroup/Vulkan-Tools#590] opened 2021-11-21 20:24 UTC
vkcube is configured such that it will only run on X11 based surfaces even when running under wayland as packaged by all linux distributions. As its a standard test utility highly available it can often lead to misrepresenting vulkan as being available on wayland compositors based on xwayland capabilities.

It would be preferable if vkcube could default to wayland if available and/or allow users to choose the surface they wish to use with flags (such that vkcube would fail to initialize if vulkan couldnt load under wayland for whatever reason).

You can see that the WSI is chosen at compile time and will be XCB by default (and no linux distribution changes this default) https://github.com/KhronosGroup/Vulkan-Tools/blob/master/cube/CMakeLists.txt#L93 . This results in the hardcoding of the WSI via `VK_USE_PLATFORM_XCB_KHR`. 

Another option would be to consider updating cmake to build an additional wayland target such as `vkcube_wayland` similar to the mesa demo's utilities `eglgears_{x11,wayland}` or the existing `vkcubepp` additional target.

**Comment by jbeich** [comment] 2021-12-08 11:05
Duplicate of #307?

> only run on X11 based surfaces even when running under wayland as packaged by all linux distributions

DragonFly and FreeBSD do have `vkcube-wayland` and `vkcube-display` since https://github.com/freebsd/freebsd-ports/commit/acc8ee9744f6.

> ` eglgears_{x11,wayland}`

`eglgears_wayland` is rotten, see [mesa-demos#16](https://gitlab.freedesktop.org/mesa/demos/-/issues/16).

**Comment by kkartaltepe** [comment] 2021-12-08 16:49
> eglgears_wayland is rotten, see mesa-demos#16.

Yes I also reached out to mesa-demos and they started to take a look at https://gitlab.freedesktop.org/mesa/demos/-/merge_requests/32 again which updates `eglgears_wayland` for modern times, which mostly works and seems discussion is revived.

> DragonFly and FreeBSD do have vkcube-wayland and vkcube-display since freebsd/freebsd-ports@acc8ee9.

It seems the maintainers for BSD are especially attentive. I doubt any other maintainers understand how vkcube cmake works and as such it would be best for vulkan-tools to provide the build targets instead of depending on maintainers to understand the repository so deeply and build that infrastructure themselves. 

> Duplicate of #307?

I think this is the alternative to providing additional build targets and arguably a better alternative but requires more work.

**Comment by ApostolosB** [comment] 2022-01-08 16:33
This is the reason vkcube and vkcubepp don't work on wayland? I don't need to file a  separate bug right?

**Comment by kkartaltepe** [comment] 2022-01-08 17:17
You would need to diagnose why vkcube doesnt work for you to know if this is the root cause or not. If you are using a wayland compositor without xwayland this may be a cause of vkcube failing to run on your system.

**Comment by ApostolosB** [comment] 2022-01-08 17:39
@kkartaltepe on weston at first it complains about DISPLAY not being set and if you assign a value to it complains about ICD missing (or something like that). On another compositor with xwayland enabled it works. 
Using the package from arch.

**Comment by Tony-LunarG** [comment] 2022-02-02 20:24
Addressed with #607

**Closed by Tony-LunarG** 2022-02-02 20:24 UTC
Labels: enhancement, vkcube

**Comment by kkartaltepe** [comment] 2022-02-03 02:04
Thanks it looks good on my machine! :+1:

**Comment by Tony-LunarG** [comment] 2022-02-03 14:30
Glad to hear it.
