### ISSUE TITLE
vulkaninfo in Windows Demos dir gets HEAP CORRUPTION error

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-Tools#314] opened 2019-12-19 19:07 UTC
Only the debug build of vulkaninfo gets this error. The release build does not.
This was found during testing of the 1.1.130 SDK. It didn't occur on all HW platforms (AMD only?)

**Comment by charles-lunarg** [comment] 2021-11-14 21:28
This is suspected to be a driver bug, as reproduction proved very difficult. It is likely to be related to the implementation of timeline semaphores, but I am in no way certain that this was the cause. As no other reports of this issue have surfaced, I am going to close the issue. Feel free to reopen it if that was not the case.

**Closed by charles-lunarg** 2021-11-14 21:28 UTC
Labels: vulkaninfo
