### ISSUE TITLE
Vullkaninfo broken in Linux- Segmentation fault 

### ISSUE THREAD

**Issue by arunsivaramanneo** [KhronosGroup/Vulkan-Tools#136] opened 2019-02-09 04:36 UTC
[vulkaninfo_Segmentation_fault.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/2847507/vulkaninfo_Segmentation_fault.txt)

**Comment by karl-lunarg** [comment] 2019-02-10 00:11
It would be really helpful to run this under a debugger and post a stack trace at the point of the fault.

**Comment by arunsivaramanneo** [comment] 2019-02-10 08:04
@karl-lunarg , i am trying to debug.. but unfortunately the following command is unable to complete without any errors.. cmake -DCMAKE_BUILD_TYPE=Debug .. 

Attaching the cMakeOutputlog, 
[CMakeOutput.log](https://github.com/KhronosGroup/Vulkan-Tools/files/2848636/CMakeOutput.log)

Note : I did report this issue few weeks back .. unfortunately i was not able to give more information

https://github.com/KhronosGroup/Vulkan-Tools/commit/01402386ecc9080f0f8e0c4e194958a0868d1027

**Comment by arunsivaramanneo** [comment] 2019-02-10 08:12
@karl-lunarg .. this is the last commit thats working fine on my linux machine

https://github.com/KhronosGroup/Vulkan-Tools/commit/e1d6a0be32144be2b378532f4183d679821234c8

**Comment by karl-lunarg** [comment] 2019-02-10 17:38
It isn't necessary to build it debuggable to get a stack trace if the trace is being used just to see where the fault occurred.  See what you did [here](https://github.com/KhronosGroup/Vulkan-Tools/commit/01402386ecc9080f0f8e0c4e194958a0868d1027#commitcomment-32041643).

I suspect that this is the same problem being discussed in this [commit](https://github.com/KhronosGroup/Vulkan-Tools/commit/01402386ecc9080f0f8e0c4e194958a0868d1027).   And I agree with the assessment in this [comment](https://github.com/KhronosGroup/Vulkan-Tools/commit/01402386ecc9080f0f8e0c4e194958a0868d1027#commitcomment-32042292):

> I'm asking because I notice that commit [3a7c6a8](https://github.com/KhronosGroup/Vulkan-Tools/commit/3a7c6a8413130d146492c688893305ff2652311a) (two commits ago) introduced the call to `vkGetPhysicalDeviceSurfaceSupportKHR` that seems to appear in the crash backtrace.

It is possible that your Intel Vulkan driver isn't handling the `vkGetPhysicalDeviceSurfaceSupportKHR` correctly, because that is where the crash is occurring.  You might try seeing if there are any updates available for your driver or contact the driver owners about the problem.

Another thing you can try is to just comment out the call to this function.  At first glance, all it does is set a boolean that is is later printed out.  After commenting it out, see if the rest of the app works.  Of course, the `supports_present` value displayed won't be right, but at least this experiment helps narrow down the problem.

**Comment by arunsivaramanneo** [comment] 2019-02-10 18:14
@karl-lunarg Thanks for the update, As you have mentioned i can confirm that the Code is working fine when i commented out the Call for vkGetPhysicalDeviceSurfaceSupportKHR. I am not sure if this info helps. I am using the latest stable Mesa drivers that are currently available. I was getting the same issue with Unstable drivers too ..

**Comment by karl-lunarg** [comment] 2019-02-10 23:43
I think I see part of the problem.  @arunsivaramanneo:  Try rebuilding with the CMake variable set to

`BUILD_WSI_XLIB_SUPPORT=OFF`

or do whatever it takes to NOT set the preprocessor symbol `VK_USE_PLATFORM_XLIB_KHR`

The idea is to turn off the Xlib support in vulkaninfo.  (Also, make sure that the call to vkGetPhysicalDeviceSurfaceSupportKHR is active again.)

If vulkaninfo works again, then the following probably explains the problem and may help @lunarpapillo and @jeremyk-lunarg.

The problem is that AppDumpSurfaceExtension() is getting called twice, once for Xcb and once for Xlib.  AppDumpSurfaceExtension() creates a surface and stores it in inst->surface.  This causes a leak because the surface isn't cleaned up until later.  But that's not the real issue.

It also means that the surface left in inst->surface is really an Xlib surface after the two calls to AppDumpSurfaceExtension()

Later, AppGpuDump() is called.  The Xcb connection to the server is still active and by the looks of the stack trace inside the Intel Vulkan driver, it is acting like it is expecting an Xcb surface.  But the surface sitting in gpu->inst->surface at this point is an Xlib surface, so the driver probably had a problem with pulling Xcb info out of the surface because it was really an Xlib surface.

The fix is to probably free the surface in AppDumpSurfaceExtension() to fix the leak.  In AppGpuDumpQueueProps, vulkaninfo might want to end up calling vkGetPhysicalDeviceSurfaceSupportKHR twice for Xcb and Xlib surfaces?   Not sure.  But it looks like it needs to be an Xcb surface the way things are set up now, instead of the Xlib surface that got left over from previous work.

I suppose there's also the possibility that the driver needs to be able to distinguish between Xcb and Xlib surfaces in this API and isn't doing so correctly for some reason.

The understanding here is not complete, but hopefully some of this helps.

**Comment by karl-lunarg** [comment] 2019-02-11 23:34
Some more data points and ideas:

* vulkaninfo runs fine on my NVIDIA driver, with the default config of XCB and XLIB support being enabled.  This implies that the NVIDIA driver is handling the call to vkGetPhysicalDeviceSurfaceSupportKHR correctly with the Xlib-based surface.  My machine is configured with only one physical device (no Intel driver).
    * This makes me feel pretty strongly that this is a driver problem, but still not totally proven.
* It might be useful to be able to repro the problem by installing the Intel driver.  Need to verify what the reporter is reporting.
* It might be useful to prepare a simple repro app, without needing vulkaninfo.  This app would just create an instance, create whatever is needed to create an Xlib surface, create the Xlib surface, and then loop through the physical devices, calling vkGetPhysicalDeviceSurfaceSupportKHR for each.  Should be about a page of code?
    * If the crash is still seen with such a simple program, then that points to a driver problem.
    * This app could be sent to the reporter to confirm that it reproduces the problem.
    * This app could be part of a bug report on the intel driver, if we think that is where the problem is.
* If there is indeed a surface leak, the validation layers should have caught it.  I suggest running vulkaninfo with validation to see if there is a report of a surface not being freed.  If there is no such report, there could be something missing in validation and reported as an issue in that repo.
    * Should check to see if we test vulkaninfo with validation in CI.

**Comment by krOoze** [comment] 2019-03-04 21:48
The window\surface is fake, so I would assume that throws off the driver.

**Comment by krOoze** [comment] 2019-03-04 23:55
My bad. I think I am using a `VkSurface` of a destroyed window. I extended the lifetime of the surface but forgot the window. Should be straightforward to fix.

**Comment by krOoze** [comment] 2019-03-04 23:58
PS: Though technically the driver should return `VK_ERROR_SURFACE_LOST_KHR`, I think.

**Comment by krOoze** [comment] 2019-03-05 02:42
Can you please verify that #153 fixes this Issue?

**Comment by jeremyk-lunarg** [comment] 2019-03-07 20:19
After merging PR #153, this issue seems to be fixed internally.
@arunsivaramanneo, if you can confirm this, that would be great.

If there is no further comment by EOB Friday, I will consider this issue resolved.

**Comment by jeremyk-lunarg** [comment] 2019-03-11 15:28
Closing.  Feel free to reopen if the issue shows up again.

**Closed by jeremyk-lunarg** 2019-03-11 15:28 UTC

**Comment by MacGamerFR** [comment] 2019-03-20 13:12
Fixed the bug, thank you ! (ArchLinux last mesa intel driver)

Now waiting for the next release and package update.

**Comment by krOoze** [comment] 2019-03-20 13:16
BTW I still think there's a faulty driver element to this. Even if we managed the platform window poorly, the driver should have returned `VK_ERROR_SURFACE_LOST_KHR` instead of crashing...
