### ISSUE TITLE
It missing a makefile in cube subdirectory

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#395] opened 2020-05-11 08:14 UTC
Hello,

It missing a makefile in cube subdirectory,

Thank you in advance to bring a makefile in cube subdirectory,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment] 2020-05-11 14:32
Closing as duplicate of #394.

**Closed by jeremyk-lunarg** 2020-05-11 14:32 UTC
