### ISSUE TITLE
it missing a makefile in layer subdirectory

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#397] opened 2020-05-11 08:34 UTC
Hello,

it missing a makefile in layer subdirectory,

Thank you in advance to bring a makefile in layer subdirectory,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment] 2020-05-11 14:33
Closing as duplicate of #394.

**Closed by jeremyk-lunarg** 2020-05-11 14:33 UTC
