### ISSUE TITLE
It missing a makefile in icd subdirectory

### ISSUE THREAD

**Issue by Azaretdodo** [KhronosGroup/Vulkan-Tools#396] opened 2020-05-11 08:33 UTC
Hello,

It missing a makefile in icd subdirectory,

Thank you in advance to bring a makefile in icd subdirectory,

Regards.

Azaretdodo.

**Comment by jeremyk-lunarg** [comment] 2020-05-11 14:33
Closing as duplicate of #394.

**Closed by jeremyk-lunarg** 2020-05-11 14:33 UTC
