### ISSUE TITLE
vkcube --c 250 sometimes doesn't display a window

### ISSUE THREAD

**Issue by davidlunarg** [KhronosGroup/Vulkan-Tools#177] opened 2019-04-15 16:10 UTC
On some systems, vkcube --c 250 runs instantly and a window is not seen. On other systems, the window is seen and runs in approximately 4.3 seconds, or 60 fps.

The problem has occurred on a Ubuntu 16.04 system with nVidia driver 418.43. (Not sure on which nVidia graphics card was used.)

The same command, run on a different Ubuntu 16.04 system with nVidia driver 418.56 with a GeForce 660Ti did not show the problem.

The problem has also been observed on Ubunty 18.04 with Intel graphics, using an older Mesa Vulkan driver.

**Comment by davidlunarg** [comment] 2019-04-15 17:01
@dustin-lunarg suggested the following:

It looks like it could be possible for the XCB implementation of cube to render before the window is mapped. I added print statements after swapchain creation and after receiving the window map notification, and see output like this:

```
Created swapchain at 500x500
Window was mapped at frame 5
```

I have seen it say the window was mapped at frame 5 a few times, but a message indicating the window was mapped at frame 0 is more common.

You could try the following with and without the 'demo->paused' assignments to see if the map notify received message is printed with a non-zero frame value when not paused, and if the pause prevents frames from being rendered until after the window is visible:

```
diff --git a/cube/cube.c b/cube/cube.c
index 3c490702..fefc30e5 100644
--- a/cube/cube.c
+++ b/cube/cube.c
@@ -1321,6 +1321,8 @@ static void demo_prepare_buffers(struct demo *demo) {
     err = demo->fpCreateSwapchainKHR(demo->device, &swapchain_ci, NULL, &demo->swapchain);
     assert(!err);
 
+    printf("Created swapchain at %dx%d\n", swapchainExtent.width, swapchainExtent.height);
+
     // If we just re-created an existing swapchain, we should destroy the old
     // swapchain at this point.
     // Note: destroying the swapchain also cleans up all its associated
@@ -2591,6 +2593,10 @@ static void demo_run_xlib(struct demo *demo) {
 static void demo_handle_xcb_event(struct demo *demo, const xcb_generic_event_t *event) {
     uint8_t event_code = event->response_type & 0x7f;
     switch (event_code) {
+        case XCB_MAP_NOTIFY:
+            printf("Window was mapped at frame %d\n", demo->curFrame);
+            demo->pause = false;
+            break;
         case XCB_EXPOSE:
             // TODO: Resize window
             break;
@@ -2623,6 +2629,7 @@ static void demo_handle_xcb_event(struct demo *demo, const xcb_generic_event_t *
                 demo->width = cfg->width;
                 demo->height = cfg->height;
                 demo_resize(demo);
+                printf("Resize to %dx%d on frame %d\n", demo->width, demo->height, demo->curFrame);
             }
         } break;
         default:
@@ -2677,6 +2684,7 @@ static void demo_create_xcb_window(struct demo *demo) {
     free(reply);
 
     xcb_map_window(demo->connection, demo->xcb_window);
+    demo->pause = true;
 
     // Force the x/y coordinates to 100,100 results are identical in consecutive
     // runs
```

**Comment by mikew-lunarg** [comment] 2019-04-15 21:22
On Windows 10 during 1.1.106 SDK prerelease testing, vkcube works as expected.

**Comment by mikew-lunarg** [comment] 2019-04-16 17:10
Using @dustin-lunarg instrumentation suggested above:
```
mikew@spork:VulkanSDK !50 0 $ time ./examples/vkcube --c 250
Created swapchain at 500x500
Window was mapped at frame 0

real	0m4.326s
user	0m0.368s
sys	0m0.684s
mikew@spork:VulkanSDK !50 0 $ 
```
By bumping up the framecount to 325, I'm able to see enough frames to perceive the animation.
C'mon by if you wish to see for yourself; it's not an easy thing to capture.

Some config info:
```
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
[     4.347] (II) NVIDIA GLX Module  418.43  Tue Feb 19 01:05:57 CST 2019
[     5.099] (II) NVIDIA(0): NVIDIA GPU GeForce GTX 950 (GM206-A) at PCI:1:0:0 (GPU-0)
```

**Comment by mikew-lunarg** [comment] 2019-04-16 17:29
A refinement to the [original description](https://github.com/KhronosGroup/Vulkan-Tools/issues/177#issue-433365474): vkcube is not running instantly.  `vkcube --c 250` executes for ~4 seconds, but the window does not appear on the screen until immediately before the application exits.

**Comment by mikew-lunarg** [comment] 2019-12-04 22:07
Same behavior on 'spork' desktop: window barely blips into view. 

- Ubuntu 16.04
- SDK 1.1.126
- GeForce GTX 950/PCIe/SSE2
- driver 4.5.0 NVIDIA 435.27.00

```
cd /home/mikew/VulkanSDK/1.1.126.0/x86_64/bin
mikew@spork:bin !23 0 $ time ./vkcube --c 250

real	0m4.350s
user	0m0.980s
sys	0m2.348s
```

**Comment by Tony-LunarG** [comment] 2019-12-04 22:16
I've tried to reproduce this dozens of time on Ubuntu 18.04, RTX 2080 440.31 without success.

**Comment by mikew-lunarg** [comment] 2019-12-17 23:20
Testing w SDK 1.1.130a1, driver 440.43.01, Ubuntu 16.04

The window mapping delay is smaller but still present.

With --c 250, the app runs a total of 4.3 seconds; rather than consuming all 4 seconds with just a quick blip of the cube, the window appears after ~3 seconds, so you can see the animation for about 1 second.

**Comment by Tony-LunarG** [comment] 2019-12-20 18:58
Can you try this patch on the system that easily reproduces this problem

[cube.txt](https://github.com/KhronosGroup/Vulkan-Tools/files/3989791/cube.txt)

**Comment by charles-lunarg** [comment] 2023-01-19 02:30
Closing issue due to age. The difficulty of recreating it makes it hard to fix, and the lack of people reporting issues makes me not think this is an issue worth solving.

If you can reproduce this issue on newer systems than what is mentioned here, feel free to reopen the issue.

**Closed by charles-lunarg** 2023-01-19 02:30 UTC
Labels: vkcube
