### ISSUE TITLE
Stuttering shortly after starting vkcube

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/Vulkan-Tools#471] opened 2020-12-05 07:49 UTC
To reproduce:

- Instrument the vkcube example with the patch below
- Build and start the `vkcube` example
- Observe a stutter after a second or two, retry if this doesn't happen quickly. 
- Observe output like this, and that the stutter happens around the same time as the (non-initial) messages

    ```
    Slow vkQueuePresentKHR (27.16ms) in frame 3
    Slow vkQueuePresentKHR (49.12ms) in frame 7
    Slow vkQueuePresentKHR (49.09ms) in frame 11
    Slow vkQueuePresentKHR (81.95ms) in frame 15
    Slow vkQueuePresentKHR (48.72ms) in frame 19
    Slow vkQueuePresentKHR (49.01ms) in frame 23
    Slow vkQueuePresentKHR (49.32ms) in frame 26
    Slow vkQueuePresentKHR (49.12ms) in frame 137
    Slow vkQueuePresentKHR (49.78ms) in frame 141
    ```

- Run with `IMMEDIATE` present mode, `vkcube --present_mode 0`
- Observe a similar slow present, also observe that the initial slow presents are absent 

    ```
    Slow vkQueuePresentKHR (12.93ms) in frame 159
    ```

System information:

```
GPU: Nvidia 2080Ti
Nvidia Driver Version: 455.46.02
uname -a: Linux orion 5.4.78 #1-NixOS SMP Wed Nov 18 18:20:34 UTC 2020 x86_64 GNU/Linux
X -version: X.Org X Server 1.20.9
gnome-shell --version: GNOME Shell 3.38.1
```

TBH I suspect that this isn't wholly a problem with the cube example.

Sounds similar to this: https://old.reddit.com/r/vulkan/comments/90049p/vk_present_mode_fifo_khr_stuttering_with_nvidia/

--------

```diff
diff --git a/cube/cube.c b/cube/cube.c
index 975f8a85..c19bfd0f 100644
--- a/cube/cube.c
+++ b/cube/cube.c
@@ -1160,7 +1160,13 @@ static void demo_draw(struct demo *demo) {
         }
     }

+    const uint64_t t1 = getTimeInNanoseconds();
     err = demo->fpQueuePresentKHR(demo->present_queue, &present);
+    const uint64_t t2 = getTimeInNanoseconds();
+    const uint64_t dt = t2 - t1;
+    const uint64_t ns_in_ms = 1000 * 1000;
+    if (dt >= 10 * ns_in_ms)
+      fprintf(stderr, "Slow vkQueuePresentKHR (%.2fms) in frame %d\n", (double)dt / ns_in_ms, demo->curFrame);
     demo->frame_index += 1;
     demo->frame_index %= FRAME_LAG;
```

**Comment by charles-lunarg** [comment] 2022-02-14 23:26
There is the possibility that this stutter is coming from outside the application itself. A while ago I installed a gnome extension that was a hardware monitor, showing CPU usage and fan speeds in the top bar. It turned out that the extension caused a whole screen refresh, and made applications appear to hitch.

The is no strong indication that this may be the case, but it is so far been unable to be reproduced, so it might be worth exploring other possibilities.

**Comment by charles-lunarg** [comment] 2023-01-19 02:42
I don't think this issue is ever going to get a satisfactory answer unfortunately.

The issue is likely due to driver shenanigans, and is difficult to reproduce. While it would be lovely to have a perfectly smooth vkcube application, that goes above and beyond its stated purpose. I have personally seen many people report issues with stuttering in various drivers on linux. It seems that vsync in linux can sometimes have a frame fall behind from unknown reasons, leading to stutters.

Thus, closing the issue is better than leaving it open only for no progress to be made in 2+ years.
Feel free to reopen if you feel it is worth pursuing.

**Closed by charles-lunarg** 2023-01-19 02:42 UTC
Labels: bug, vkcube

**Comment by cej48** [comment] 2023-10-23 23:16
> There is the possibility that this stutter is coming from outside the application itself. A while ago I installed a gnome extension that was a hardware monitor, showing CPU usage and fan speeds in the top bar. It turned out that the extension caused a whole screen refresh, and made applications appear to hitch.

What a great punt, turned out I had the exact issue with the performance monitor on my xfce desktop.
